### ISSUE TITLE
CSS incorrectly linked

### ISSUE THREAD

**Issue by ad3429** [Gino1212/prj-rev-bwfs-dasmoto#1]
https://github.com/Gino1212/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Craft/index.html#L5

It seems that you incorrectly linked to your CSS by linking to a local file on your computer -- this would allow you to view it on your own computer, but will cause trouble when people from other computers attempt to view your webpage. You can instead link directly to your resources folder, like so:

<img width="489" alt="screen shot 2017-08-24 at 8 31 56 pm" src="https://user-images.githubusercontent.com/25671399/29694578-49cf55a0-890b-11e7-9279-a2ee8cd68a6a.png">

**Comment by Gino1212** [comment]
Thanks for reviewing this first project, and thank you for the feedback!
